# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a19522f48d68a67ec8a5a1d00d33f34a76dd57123109f68664b27bc6c2513eff46439b975854b23711fecf5caedb4c4371cdfa3cf9d550fd8220b2dbc63bcb2f
  facebook_app_id: "1596684027214467"
  facebook_app_secret: <%= ENV["facebook_app_secret"] %>

test:
  secret_key_base: 40542fb9fbab19489b158b4a3ae21939a28fd4fd878c40fe24e08ba71d418eb473561889910c3be86372a25d5c05f219283422b866867688d15411659f2da178

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: "1596684027214467"
  facebook_app_secret: <%= ENV["facebook_app_secret"] %>


